package io.legado.app.lib.theme

import android.graphics.Color
import androidx.annotation.ColorInt

/**
 * Immutable snapshot of all runtime theme colors.
 * Generated by [ThemeStore.readAllColors] and cached in memory.
 */
data class ThemeColors(
    // Basic colors
    @param:ColorInt val primaryColor: Int,
    @param:ColorInt val primaryColorDark: Int,
    @param:ColorInt val accentColor: Int,
    @param:ColorInt val statusBarColor: Int,
    @param:ColorInt val navigationBarColor: Int,
    @param:ColorInt val textColorPrimary: Int,
    @param:ColorInt val textColorPrimaryInverse: Int,
    @param:ColorInt val textColorSecondary: Int,
    @param:ColorInt val textColorSecondaryInverse: Int,
    @param:ColorInt val backgroundColor: Int,
    @param:ColorInt val bottomBackground: Int,
    // M3 tokens
    @param:ColorInt val colorOnPrimary: Int,
    @param:ColorInt val colorPrimaryContainer: Int,
    @param:ColorInt val colorOnPrimaryContainer: Int,
    @param:ColorInt val colorSecondaryContainer: Int,
    @param:ColorInt val colorOnSecondaryContainer: Int,
    @param:ColorInt val colorSurface: Int,
    @param:ColorInt val colorOnSurface: Int,
    @param:ColorInt val colorSurfaceVariant: Int,
    @param:ColorInt val colorOnSurfaceVariant: Int,
    @param:ColorInt val colorSurfaceContainer: Int,
    // Flags
    val coloredStatusBar: Boolean,
    val coloredNavigationBar: Boolean,
    val autoGeneratePrimaryDark: Boolean,
) {
    companion object {
        /**
         * Safety-net default used as initial StateFlow value.
         * Replaced by [ThemeManager.refresh] on app startup before any UI is shown.
         */
        val DEFAULT = ThemeColors(
            primaryColor = 0xFF455A64.toInt(),
            primaryColorDark = 0xFF37474F.toInt(),
            accentColor = 0xFF263238.toInt(),
            statusBarColor = 0xFF455A64.toInt(),
            navigationBarColor = Color.WHITE,
            textColorPrimary = 0xDE000000.toInt(),
            textColorPrimaryInverse = 0xFFFFFFFF.toInt(),
            textColorSecondary = 0x8A000000.toInt(),
            textColorSecondaryInverse = 0xB3FFFFFF.toInt(),
            backgroundColor = Color.WHITE,
            bottomBackground = Color.WHITE,
            colorOnPrimary = Color.WHITE,
            colorPrimaryContainer = 0xFFD9E3E6.toInt(),
            colorOnPrimaryContainer = 0xFF2C3A3E.toInt(),
            colorSecondaryContainer = 0xFFD9E1E3.toInt(),
            colorOnSecondaryContainer = 0xFF2C3638.toInt(),
            colorSurface = Color.WHITE,
            colorOnSurface = 0xDE000000.toInt(),
            colorSurfaceVariant = 0xFFE6E9EC.toInt(),
            colorOnSurfaceVariant = 0x8A000000.toInt(),
            colorSurfaceContainer = 0xFFECEEF0.toInt(),
            coloredStatusBar = true,
            coloredNavigationBar = false,
            autoGeneratePrimaryDark = true,
        )
    }
}
